### ISSUE TITLE
Latexify

### ISSUE THREAD

**Issue by gustaphe** [rmsrosa/UnitfulBuckinghamPi.jl#3]
The README mentions a workaround for Latexify, which I think is (now?) unnecessary:
`latexify(Π)` and `latexify(Π_str)` both give
![Pi](https://user-images.githubusercontent.com/6677110/170648275-43e6f783-ca65-44b4-a8c8-d05f5cb45b07.png)

**Comment by rmsrosa** [comment]
Oh, nice! I will have a look when I come back from a trip. Thanks!

**Comment by rmsrosa** [comment]
Thanks, I have just updated the README to reflect that!
